### ISSUE TITLE
Failed to setup python environment  through environment.yml

### ISSUE THREAD

**Issue by wzeyuann** [davide-coccomini/Combining-EfficientNet-and-Vision-Transformers-for-Video-Deepfake-Detection#11]
Initially, I want to setup python environment through `conda env create --file environment.yml`. However, there are something wrong with the version.
![image](https://user-images.githubusercontent.com/46087050/144234745-14255702-41f8-4948-83fb-00ed80d8676e.png)
Then I delete the  concrete version of the packages. But there occurred something wrong new.

So could you please check wether there are something wrong in the environment file.

**Comment by yuan-yuan321** [comment]
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/46087050/144414450-1e405f49-0b86-49ff-8a72-3e1c3f859449.png">

**Comment by yuan-yuan321** [comment]
Looking forward to your answer, thank you~

**Comment by nrohan09-cloud** [comment]
I am facing this exact same issue.

**Comment by davide-coccomini** [comment]
Hello! Sorry for the late reply, I should have solved the problem with the last commit. Let me know if you encounter any other problems.

**Comment by xiaomo9** [comment]
> New errors <img alt="微信图片_20211202193533" width="794" src="https://user-images.githubusercontent.com/46087050/144414767-dbf80b6a-7636-4b9d-a19f-6591039a633b.png">
> 
> >

I wonder if you solved it，I had the same problem
