### ISSUE TITLE
Unable to download pretrained model

### ISSUE THREAD

**Issue by karthik1145** [davide-coccomini/Combining-EfficientNet-and-Vision-Transformers-for-Video-Deepfake-Detection#12]
Hi @davide-coccomini , 
I have been trying to download the pretrained model using the wget command, it throws an error 'unable to resolve host'. Could you please help me to download the pretrained model?
Thanks

**Comment by davide-coccomini** [comment]
Hi @karthik1145,
Excuse us for the issue, we are working to restore the server, the weights will be available again as soon as possible.

**Comment by karthik1145** [comment]
Hey @davide-coccomini , could you share the weights over google drive for now? Or you suggest waiting until server is up? 
Thanks

**Comment by davide-coccomini** [comment]
I uploaded the weights on Google Drive, let me know if you need something more. I will soon update also the README to give this alternative to everyone.

https://drive.google.com/drive/folders/19bNOs8_rZ7LmPP3boDS3XvZcR1iryHR1?usp=sharing

Good luck with your research!

**Comment by karthik1145** [comment]
Hey David. Thank you so much for taking up the additional burden of uploading to drive. Thank you for your support!.

**Comment by davide-coccomini** [comment]
> Hey David. Thank you so much for taking up the additional burden of uploading to drive.
> 
> Thank you for your support!.

No problem! If you need anything else let me know.
