### ISSUE TITLE
Which version of FF++ did you use?

### ISSUE THREAD

**Issue by IItaly** [davide-coccomini/Combining-EfficientNet-and-Vision-Transformers-for-Video-Deepfake-Detection#13]
Hello. @davide-coccomini  Thanks for your work.
I want to know which compression version dataset you used to train and test the modal. FF++ C23 or FF++ C40?

**Comment by davide-coccomini** [comment]
Hi @IItaly we used C23 dataset.

**Comment by IItaly** [comment]
> Hi @IItaly we used C23 dataset.

Thank you. And which level of results did you report in the paper? Frame or Video?

**Comment by davide-coccomini** [comment]
> > Hi @IItaly we used C23 dataset.
> 
> Thank you. And which level of results did you report in the paper? Frame or Video?

You're welcome! In the paper, we report the video-level metrics.
