### ISSUE TITLE
data set

### ISSUE THREAD

**Issue by zhuzhen1996** [davide-coccomini/Combining-EfficientNet-and-Vision-Transformers-for-Video-Deepfake-Detection#15]
Hello, does your preprocessing code support using only the FaceForensics++ dataset?When I run your code for detecting faces, I get the above error
![image](https://user-images.githubusercontent.com/55490753/155638266-b024c45f-a497-4b9e-969e-401cf9080f54.png)
This is where my dataset is stored
![1645753754(1)](https://user-images.githubusercontent.com/55490753/155638333-1e1b8d6e-d717-41b3-b856-42f269b3fdff.png)

**Comment by davide-coccomini** [comment]
Could you please show me the whole error log and the complete used command?

**Comment by zhuzhen1996** [comment]
Because I am currently running on the Windows system, I inquired about the relevant information, which may be caused by the parameters in the dataloader.
![1645950288(1)](https://user-images.githubusercontent.com/55490753/155874654-95ca9d84-6b53-4d3a-962b-def5fde47d27.png)
The incoming parameter collate_fn uses a lambda expression

**Comment by zhuzhen1996** [comment]
I want to understand, I input the command to process the dataset FaceForensics++ alone, and your code doesn't seem to run.

**Comment by zhuzhen1996** [comment]
I switched to a linux system and re-run your code. The following error occurred
![image](https://user-images.githubusercontent.com/55490753/155874931-aaccbc8c-2a00-4d0f-8a55-891d986922a4.png)
![1645950856(1)](https://user-images.githubusercontent.com/55490753/155874954-74684e2e-f1cd-47a2-8083-95bde4de0f88.png)

**Comment by davide-coccomini** [comment]
Could you please send me the screen of the exact command you run and the data folder content?

**Comment by zhuzhen1996** [comment]
Hello, I wrote directly in the code without entering the command line.
This is the structure of the FaceForensics++ dataset in my windows system
![1646119120(1)](https://user-images.githubusercontent.com/55490753/156122867-fd513f4f-2e8a-4bb2-9c7c-8269753bada2.png)
![1646119143(1)](https://user-images.githubusercontent.com/55490753/156122921-01ac973e-efde-414c-a502-aa5e83c2af52.png)

**Comment by davide-coccomini** [comment]
I think the problem stems from the contents of those folders in the second screen. In particular, DeepFakeDetection I believe has a different structure than the others. We also did not use that piece of dataset for our experiments. Remove that folder and leave only Deepfakes, Face2Face, FaceShifter, FaceSwap and NeuralTextures, which all have the same structure.

**Comment by zhuzhen1996** [comment]
I deleted the extra folder and it still gives the same error when Windows is running。

**Comment by davide-coccomini** [comment]
This probably is a Windows-specific problem, see that: https://stackoverflow.com/questions/59168477/cant-find-starting-number-in-the-name-of-file-when-trying-to-read-frames-fr

**Comment by davide-coccomini** [comment]
Did you solve it?
