### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by yueanga** [davide-coccomini/Combining-EfficientNet-and-Vision-Transformers-for-Video-Deepfake-Detection#16]
sorry but I had some problems in creating the environment, can you give me some advice about this issue?
I followed your command
> conda env create --file environment.yml -n deepfakesreate --file environment.yml -n deepfakes
and delete below lines in environment.yml
> name:deepfakes(first line)
> prefix:......(last line)
thank you so much and looking forward to your reply

**Comment by yueanga** [comment]
![image](https://user-images.githubusercontent.com/46816762/157147821-c18898ad-bc37-42d7-9c88-84b638bb1ecf.png)
![image](https://user-images.githubusercontent.com/46816762/157147946-c0606f5c-a415-4358-9804-107cbcce7650.png)

**Comment by iwsylit** [comment]
Make sure you've installed CMake and it is in your PATH.

**Comment by czy5638222** [comment]
export PYTHONPATH=.

What is the purpose of this step please? What should I add in the back?

**Comment by davide-coccomini** [comment]
Hi @czy5638222, you can read more about it here: https://bic-berkeley.github.io/psych-214-fall-2016/using_pythonpath.html
