### ISSUE TITLE
Dateset

### ISSUE THREAD

**Issue by czy5638222** [davide-coccomini/Combining-EfficientNet-and-Vision-Transformers-for-Video-Deepfake-Detection#18]
hello, i typed this command but why doesn't the system respond
![image](https://user-images.githubusercontent.com/58411298/158124979-8a5dc2b1-3645-45cf-8d81-d87ff29356f2.png)
![image](https://user-images.githubusercontent.com/58411298/158125145-b1ac32fe-ab06-479f-8f60-53597b0dbc54.png)
![image](https://user-images.githubusercontent.com/58411298/158125171-9557dbcb-55f6-4015-a929-4c74a170761e.png)
 can you help me see what's wrong
thanks！

**Comment by czy5638222** [comment]
![814590dd36f308ab98c11aa1e482846](https://user-images.githubusercontent.com/58411298/158137010-874a6f14-2328-4669-aa74-373c68f55faa.png)
 oh sorry， I send wrong 
still no response

**Comment by davide-coccomini** [comment]
Could you try to replace the --data_path with "../FACEFORENSICS"?

**Comment by czy5638222** [comment]
![image](https://user-images.githubusercontent.com/58411298/158333747-f93e1d88-6ab7-4f8f-aecc-67a5ea15f4bb.png)
**Hello, please take a look at this situation, what should I do?**

**Comment by czy5638222** [comment]
There are problems with both opencv and thresholds
I have set the thresholds low
And the opencv problem mentioned in the error
Can you help me take a look? 

![image](https://user-images.githubusercontent.com/58411298/158346190-6c0d5eee-2d6e-4a01-be93-ca8550b3932f.png)

**Comment by davide-coccomini** [comment]
Change the --dataset parameter to Faceforensics, it is set by default to DFDC

**Comment by czy5638222** [comment]
![image](https://user-images.githubusercontent.com/58411298/158358401-4bc6619e-a17a-433f-8855-9625648827cf.png)
 
![image](https://user-images.githubusercontent.com/58411298/158358530-ac53ffc4-00ad-4843-9e0d-c3cce01f915a.png)


Is the dataset download this?

**Comment by davide-coccomini** [comment]
Yes and you have to set --dataset to "FACEFORENSICS" otherwise the code will try to adapt to the structure of DFDC.

**Comment by czy5638222** [comment]
![image](https://user-images.githubusercontent.com/58411298/158359328-9d688173-51b2-4d1f-8b96-19f97162af60.png)
 It's already

**Comment by czy5638222** [comment]
![image](https://user-images.githubusercontent.com/58411298/158361280-e1236bbc-ea16-4fe2-93e0-ebd1896f2b8c.png)
threshold is low
I don't know why it just doesn't work
please help me

**Comment by davide-coccomini** [comment]
It is not correctly reading the videos. Did you executed the command with the correct --dataset parameter?

**Comment by czy5638222** [comment]
is that correct 


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dataset', default="FACEFORENSICS",type=str,
                        help='Dataset (DFDC / FACEFORENSICS)')
    parser.add_argument('--data_path', default='', type=str,
                        help='Videos directory')
    parser.add_argument("--detector-type", help="type of the detector", default="FacenetDetector",
                        choices=["FacenetDetector"])
                        
    opt = parser.parse_args()
    print(opt)

**Comment by czy5638222** [comment]
how to execute code twice 
Can you tell me the specific steps? 
thanks！！！

**Comment by czy5638222** [comment]
![image](https://user-images.githubusercontent.com/58411298/158406151-01c70eb5-e272-4a0f-976e-c9c4ff4347c0.png)


![image](https://user-images.githubusercontent.com/58411298/158406634-d53e089b-0bf3-4dad-8230-a9213b17be1c.png)

**Comment by czy5638222** [comment]
What should I do in the above situation?

**Comment by davide-coccomini** [comment]
I pushed a fix for the utils.py file. You should now be able to detect all the faces after pulling my changing using the following command:
`python3 detect_faces.py --dataset FACEFORENSICS --data_path ../FACEFORENSICS
`

**Comment by czy5638222** [comment]
I copied your latest utils.py but it still looks like this
![image](https://user-images.githubusercontent.com/58411298/158513043-a41f0028-f3b9-4fc4-b272-4761eae8ff4d.png)

**Comment by czy5638222** [comment]
Hey 
you look at this
Is it because of my dataset error?
Because there is a face in the dataset of actor, he can extract it
Other datasets don't seem to have faces, so an error is reported saying that faces cannot be detected

![image](https://user-images.githubusercontent.com/58411298/158567757-72294bde-5345-4b45-8326-a8a6e7d55658.png)
![image](https://user-images.githubusercontent.com/58411298/158567810-2838c210-888d-486d-b6aa-d5c081a912b2.png)

**Comment by davide-coccomini** [comment]
You should remove folders like "boxes" from the video folders. "actors" should already be skipped but you have to be sure to not have "boxes" also in other folders. The correct structure of the dataset is:

- FACEFORENSICS
       - manipulated_sequences
                 - Deepfakes
                        - c23
                               - videos
                                       000_003.mp4
                                       ....
                                       999_960.mp4
                    ...
                    NeuralTextures
                           ....
         - original_sequences
                     - youtube
                           - c23
                                  - videos
                                         000.mp4
                                         ...
                                         999.mp4

And nothing else. The "boxes" folder will be automatically created inside "FACEFORENSICS" folder and you need to remove any additional folder you may have in other positions. The expected folders inside manipulated_sequences are Deepfakes, Face2Face, FaceShifter, FaceSwap and NeuralTextures.

**Comment by czy5638222** [comment]
![image](https://user-images.githubusercontent.com/58411298/158594953-968ddad2-7536-47b9-a7ab-227d02fde678.png)
I deleted all boxes
but still

**Comment by davide-coccomini** [comment]
It seems like it is trying to read the folders as videos instead of looking inside these folders. Are you totally sure that you have the last version of the repository?

**Comment by czy5638222** [comment]
is the repository inside environment.yml?
Can you see which ones are the latest?

**Comment by davide-coccomini** [comment]
Just remove the old version you cloned and run again the command:
`https://github.com/davide-coccomini/Combining-EfficientNet-and-Vision-Transformers-for-Video-Deepfake-Detection.git`

I just tried cloning the repository and running it and it works.

**Comment by czy5638222** [comment]
![image](https://user-images.githubusercontent.com/58411298/158601322-c47188f5-fae3-484f-8352-5a0ec79b88d1.png)
 That's it now

**Comment by czy5638222** [comment]
![image](https://user-images.githubusercontent.com/58411298/158603617-2d19db63-c817-446c-8f0e-e2cf937a682b.png)


Still the same!

**Comment by davide-coccomini** [comment]
This is related to multiprocessing. Probably your system has some peculiarity that cause this error. You can try to change num_workers from 40 to 1 inside detect_faces.py line 22. I will provide an option so that it will be customizable.

**Comment by czy5638222** [comment]
![image](https://user-images.githubusercontent.com/58411298/158604094-1a0f8710-9853-46ad-8e5c-298fe1b1468d.png)


I got a new error after I changed it to 1

**Comment by czy5638222** [comment]
![image](https://user-images.githubusercontent.com/58411298/158608018-d5d6c513-8feb-4cf9-8794-e6432b660e40.png)
Relative paths don't seem to work at all

**Comment by czy5638222** [comment]
I changed the path to ..\videos
It runs successfully and the boxes are placed directly inside the videos
Please do I copy all the boxes to a folder or keep it as it is
![image](https://user-images.githubusercontent.com/58411298/158752425-4e432172-023f-40a6-9952-becbacf54d81.png)
