### ISSUE TITLE
How to get the pretrained model?

### ISSUE THREAD

**Issue by abhishekju06** [davide-coccomini/Combining-EfficientNet-and-Vision-Transformers-for-Video-Deepfake-Detection#2]
@davide-coccomini 
 wget ...
--2021-09-10 21:44:46--  http://.../
Resolving ... (...)... failed: Name or service not known.
wget: unable to resolve host address ‘...’

I'm stuck with downloading the pre trained model.

**Comment by davide-coccomini** [comment]
Hi, the wget command is not complete. I am uploading the models and I will update the README with the correct and complete command. Keep an eye on the repository in the next few hours.

**Comment by davide-coccomini** [comment]
You can now find the correct wget command in the updated Readme.
