### ISSUE TITLE
extract_crops

### ISSUE THREAD

**Issue by czy5638222** [davide-coccomini/Combining-EfficientNet-and-Vision-Transformers-for-Video-Deepfake-Detection#20]
![image](https://user-images.githubusercontent.com/58411298/159145382-e6fce691-4d85-4b65-9e58-40e5aaed4323.png)

**Hi, what is the problem?
how do i fix it**

**Comment by czy5638222** [comment]
Error: Error:name 'opt' is not defined

what to do with this question

**Comment by davide-coccomini** [comment]
As you have seen in the previous issue, please, use relative paths and see if the error still occurs.

**Comment by czy5638222** [comment]
How can I use relative paths?
Can you teach me or how should I write

**Comment by czy5638222** [comment]
The error is this

![image](https://user-images.githubusercontent.com/58411298/160348858-b5c01f94-510f-42cb-83a7-a4d502818c9b.png)

**Comment by JiangdongWang123** [comment]
![微信图片_20220520163650](https://user-images.githubusercontent.com/104985732/169489035-d5f6a714-8bf4-4441-85c6-1959ecea0816.png)
hello！I have the same problem.   NameError: name 'e' is not defined. And I've already used relative paths, how do i fix it?
