### ISSUE TITLE
train_

### ISSUE THREAD

**Issue by czy5638222** [davide-coccomini/Combining-EfficientNet-and-Vision-Transformers-for-Video-Deepfake-Detection#21]
![image](https://user-images.githubusercontent.com/58411298/161413679-f2892855-fc26-485f-a2e8-9d2776d640d0.png)

Can you take a look at this question? Can you help me?

**Comment by davide-coccomini** [comment]
I am not able to reproduce your error. Are you sure you are using the right environment?

**Comment by davide-coccomini** [comment]
Can you show me the whole output?

**Comment by yang1284863413** [comment]
Hi, have you resolved this issue?
