### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by Elijah-Yi** [davide-coccomini/Combining-EfficientNet-and-Vision-Transformers-for-Video-Deepfake-Detection#22]
Thanks for your contribution @davide-coccomini 
I have some questions about the training data，
![image](https://user-images.githubusercontent.com/22116117/161907627-38f807fb-85ba-4e3b-aac5-348819e46e31.png)
In the sixth line of script **utils.py** . Why did you filter out  the part of "DeepFakeDetection" and  "actors"?
Looking forward to your reply, thanks again!

**Comment by davide-coccomini** [comment]
Hi Elijah. The videos inside these folders seem to give format problems during detection. We used all the others for training our method.

**Comment by Elijah-Yi** [comment]
I see and  thanks for your answer
