### ISSUE TITLE
extract error

### ISSUE THREAD

**Issue by X-tan58** [davide-coccomini/Combining-EfficientNet-and-Vision-Transformers-for-Video-Deepfake-Detection#25]
![image](https://user-images.githubusercontent.com/95734189/164911323-7c5dc6ef-e8b9-4e78-9368-a2db70f15393.png)
I used the Celeb dataset, but changed the format of the Celeb dataset to f ++ to be consistent with your code. The folder architecture for storing videos and the folder architecture for storing face pictures are shown in the figure.The photo with the train folder is the folder that holds the face image.
![image](https://user-images.githubusercontent.com/95734189/164911518-1cc72ab7-dc73-46fd-a947-653abe05dd33.png)

**Comment by X-tan58** [comment]
I confirmed that the number of files in the box is equal to the number of my videos by the command you gave, but I encountered the error as shown in the picture. Why did I get this wrong? When I deleted the video he reported the error and ran it again, he suggested another video encountered the same error. I don't think I can delete it one by one according to his hints, so I would like to request your help

**Comment by X-tan58** [comment]
I just added the absolute path to the folder where the video is stored and the folder where the images are extracted to the extract.py file you gave me,and I didn't make any other changes.

**Comment by davide-coccomini** [comment]
Hi. Could you please share the exact command you used and the error shown?

**Comment by X-tan58** [comment]
![image](https://user-images.githubusercontent.com/95734189/164969517-7049396e-5f50-4013-b311-6254628e65fd.png)
This is the error

**Comment by X-tan58** [comment]
![image](https://user-images.githubusercontent.com/95734189/164969663-d52f7e2a-b4bd-4d1c-8d24-2b50fc5c4b07.png)
The red line is the absolute path THAT I added,Corresponding to the folder structure on the left

**Comment by X-tan58** [comment]
![image](https://user-images.githubusercontent.com/95734189/164969964-bcabfded-3924-4a41-a46d-10339c1dea99.png)
This is the command to check the number of files in the box

**Comment by X-tan58** [comment]
the number of my video is also the same 1200.
