### ISSUE TITLE
extract error

### ISSUE THREAD

**Issue by X-tan58** [davide-coccomini/Combining-EfficientNet-and-Vision-Transformers-for-Video-Deepfake-Detection#26]
I only have Celeb data set now, and the folder structure of CeleB is shown in the figure. But I managed to extract the box file in DETECt_face. py. Please see if that's the case.and I set  "--dataset=DFDC". But when I execute extract. Py, I get the following error. I wonder if it has something to do with my folder structure.I wish your help!
![image](https://user-images.githubusercontent.com/95734189/165013437-32ef6507-e96a-4c45-830d-dd83f5c4a2cf.png)

**Comment by X-tan58** [comment]
![image](https://user-images.githubusercontent.com/95734189/165013638-7da82921-9ad2-4322-8d2f-0ccf9ab77873.png)
![image](https://user-images.githubusercontent.com/95734189/165013652-05ff84f5-42c4-4df1-867d-cb297eb47d34.png)

**Comment by X-tan58** [comment]
iIf this is really the cause of the folder structure, can you provide me with the structure of DFDC data set, because I don't know its structure

**Comment by X-tan58** [comment]
I have to say,it is so hard to run a code successfully for me!  I tried your method moving the boxes file and use relative path of the --data path.but raise the error cann't find the file .I still use the absolute path ,he give me the same error too.By the way ,can you check whether I have done something wrong,?

![image](https://user-images.githubusercontent.com/95734189/165113513-558a6d1f-08ab-4d8c-889d-4a98699548bf.png)
![image](https://user-images.githubusercontent.com/95734189/165115147-d8f189e1-f39f-4c8b-9d02-01a423ac1d1c.png)

**Comment by davide-coccomini** [comment]
> I have to say,it is so hard to run a code successfully for me! I tried your method moving the boxes file and use relative path of the --data path.but raise the error cann't find the file .I still use the absolute path ,he give me the same error too.By the way ,can you check whether I have done something wrong,?
> 
> ![image](https://user-images.githubusercontent.com/95734189/165113513-558a6d1f-08ab-4d8c-889d-4a98699548bf.png) ![image](https://user-images.githubusercontent.com/95734189/165115147-d8f189e1-f39f-4c8b-9d02-01a423ac1d1c.png)

The error says that "Celeb/Celeb-fake" does not exists. This is probably because the "extract_crops.py" is inside preprocessing folder so if you execute the Python code from that directory the correct path should be "../Celeb/Celeb-fake".

**Comment by davide-coccomini** [comment]
Did you solved?

**Comment by X-tan58** [comment]
Thank you for your concern very much! . I have to put it down temporarily because of some other urgent work. I'll take a closer look at this code later, and your work is very inspiring.

**Comment by SuperCarryFu** [comment]
I hope you don't close this question, and I'm trying

**Comment by skg4463** [comment]
Hello, I have found a solution to the problem.

-extract_crops.py
![image](https://user-images.githubusercontent.com/45844164/167560323-f4fb89e0-ce14-4192-b032-c65b3497601b.png)

It was now a problem that the value of the Paths returned here was None. (on DFDC based)

Check out the utils.py, get_video_paths package.

-utils.py
![image](https://user-images.githubusercontent.com/45844164/167560795-e23c5d3c-2331-4806-88b9-5083a906b7f7.png)
Here I was able to confirm that the name of each video should be extended to "video_path" but it does not work normally.

list.extend() function does not have the return value.

So.
![image](https://user-images.githubusercontent.com/45844164/167561157-204ccee8-b027-44c8-8aa2-d0715f3b6349.png)
If you modify the function as above, you can see that it works normally.

![image](https://user-images.githubusercontent.com/45844164/167561686-54afac0a-b48f-49e7-a156-ad49e6ef3d02.png)

Thank You.

**Comment by davide-coccomini** [comment]
I updated the repository with the fix proposed by @skg4463, thank you!

**Comment by TimeSavingZzz** [comment]
thank you! @skg4463
