### ISSUE TITLE
extract face not working on faceforensics dataset

### ISSUE THREAD

**Issue by abhijeeetkumar** [davide-coccomini/Combining-EfficientNet-and-Vision-Transformers-for-Video-Deepfake-Detection#28]
Hi Can you help? im not able to extract all the faces from dataset/

(deepfakes) e5-cse-344-30:/home/mdl/amk7371/Combining-EfficientNet-and-Vision-Transformers-for-Video-Deepfake-Detection/preprocessing> python3 detect_faces.py --data_path ../../faceforensics/ --dataset FACEFORENSICS
Namespace(data_path='../../faceforensics/', dataset='FACEFORENSICS', detector_type='FacenetDetector', processes=8)
  8%|████████████▏                                                                                                                                                    | 713/9431 [33:02<9:24:36,  3.89s/it]

 11%|█████████████████                                                                                                                                              | 1014/9431 [48:43<26:15:58, 11.23s/it]Traceback (most recent call last):
  File "/home/mdl/amk7371/x86_64/envs/deepfakes/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
  File "/home/mdl/amk7371/x86_64/envs/deepfakes/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/mdl/amk7371/x86_64/envs/deepfakes/lib/python3.7/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

**Comment by davide-coccomini** [comment]
Can you show me the folders structure?

**Comment by skg4463** [comment]
-extract_crops.py
![image](https://user-images.githubusercontent.com/45844164/167560323-f4fb89e0-ce14-4192-b032-c65b3497601b.png)

It was now a problem that the value of the Paths returned here was None. (on DFDC based)

Check out the utils.py, get_video_paths package.

-utils.py
![image](https://user-images.githubusercontent.com/45844164/167560795-e23c5d3c-2331-4806-88b9-5083a906b7f7.png)
Here I was able to confirm that the name of each video should be extended to "video_path" but it does not work normally.

list.extend() function does not have the return value.

So.
![image](https://user-images.githubusercontent.com/45844164/167561157-204ccee8-b027-44c8-8aa2-d0715f3b6349.png)
If you modify the function as above, you can see that it works normally.

![image](https://user-images.githubusercontent.com/45844164/167561686-54afac0a-b48f-49e7-a156-ad49e6ef3d02.png)

Thank You.

**Comment by davide-coccomini** [comment]
Thank you @skg4463, I updated the repository!

**Comment by paolotarantino** [comment]
Hi, I'm trying to run detect_faces.py on FACEFORENSICS but this problem still occurs. Any suggestions ?

**Comment by davide-coccomini** [comment]
Yes, it happens with the actors folder because seems there are some strange formatted videos. Skip this directory.
