### ISSUE TITLE
Test dataset arrangement issues

### ISSUE THREAD

**Issue by abhishekju06** [davide-coccomini/Combining-EfficientNet-and-Vision-Transformers-for-Video-Deepfake-Detection#3]
Hi @davide-coccomini , 
I have arranged the folders as depicted below 

- deep_fakes
         dataset
            test_set  
                        ...manipulated_sequences : fake videos
                        ...original_sequences : the original videos
                        
  Now, I am working on FaceForensic data for only 5 videos (I intended to run the pre-trained model)
  With help of extract_crop.py I managed to crop the faces from the manipulated Videos.
My Queries:  
1) What would the **Original** folder contain and where would that be present  in this scenario of my file structure?
2) The command that I ran is
!python3 test.py --model_path "cross_efficient_vit.pth" --config "configs/architecture.yaml" --dataset "FACEFORENSICS" --workers 2 --batch_size 1

I changed the code for test.py : below the code snippet is present
def get_method(video, data_path):
    **temp = os.path.join(data_path, "manipulated_sequences").split('../')[-1]**
    #methods = os.listdir(os.path.join(data_path, "manipulated_sequences"))
    methods = os.listdir(temp)
    print(methods)
    **temp1 = os.path.join(data_path, "original_sequences").split('../')[-1]**
    #methods.extend(os.listdir(os.path.join(data_path, "original_sequences")))
    methods.extend(os.listdir(temp1))
    methods.append("DFDC")**#Why should DFDC be added as I work with FACEFORENSIC data**
    methods.append("Original")
    selected_method = ""
    for method in methods:
        if method in video:
            selected_method = method
            break
    return selected_method

Please help!

**Comment by davide-coccomini** [comment]
Hi. 

1) The original folder derives from the structure of FaceForensics++ which has also an Original folder with the original videos from which the manipulated ones are obtained. If you want to use also them to test (you should do since otherwise working with only fake videos a classifier that always classifies "FAKE" would have perfect accuracy) you have to put the "Original" folder in the same directory as the others (Face2Face, NeuralTextures etc.).

2) The "get_method" function is used to obtain the method of the current video (Face2Face, NeuralTextures, ..., Original, DFDC) from the file path. This function is used for both DFDC and FaceForensics++ dataset so it is needed to check DFDC too.

**Comment by abhishekju06** [comment]
Can you please tell me where would the cropped images from the manipulated videos be present in the file structure during testing?

**Comment by abhishekju06** [comment]
I did arrange the folders as per your suggestion and executed  the command:

python3 test.py --model_path "cross_efficient_vit.pth" --config "configs/architecture.yaml" --dataset "Deepfakes" --workers 2 --batch_size 1 --max_videos 0

This is the console output:

Namespace(batch_size=1, config='configs/architecture.yaml', dataset='Deepfakes', efficient_net=0, frames_per_video=30, max_videos=0, model_path='cross_efficient_vit.pth', workers=2)
Loaded pretrained weights for efficientnet-b0
Loaded pretrained weights for efficientnet-b0
100%|██████████████████████████████████████████| 10/10 [00:00<00:00, 102.31it/s]
extIOWrapper name=**'Deepfakes_cross_efficient_vit.pth_labels.txt' mode='a' encoding='UTF-8'>** 
Predicting |###                             | 1/10Traceback (most recent call last):
  File "test.py", line 275, in <module>
    video_pred = video_faces_preds[0]
IndexError: list index out of range
[?25h

I traced the program and saw that there is no such file **Deepfakes_cross_efficient_vit.pth_labels.txt**.
Can you please help? @davide-coccomini @mesnico

**Comment by abhishekju06** [comment]
> I did arrange the folders as per your suggestion and executed the command:
> 
> python3 test.py --model_path "cross_efficient_vit.pth" --config "configs/architecture.yaml" --dataset "Deepfakes" --workers 2 --batch_size 1 --max_videos 0
> 
> This is the console output:
> 
> Namespace(batch_size=1, config='configs/architecture.yaml', dataset='Deepfakes', efficient_net=0, frames_per_video=30, max_videos=0, model_path='cross_efficient_vit.pth', workers=2)
> Loaded pretrained weights for efficientnet-b0
> Loaded pretrained weights for efficientnet-b0
> 100%|██████████████████████████████████████████| 10/10 [00:00<00:00, 102.31it/s]
> extIOWrapper name=**'Deepfakes_cross_efficient_vit.pth_labels.txt' mode='a' encoding='UTF-8'>**
> Predicting |### | 1/10Traceback (most recent call last):
> File "test.py", line 275, in
> video_pred = video_faces_preds[0]
> IndexError: list index out of range
> �[?25h
> 
> I traced the program and saw that there is no such file **Deepfakes_cross_efficient_vit.pth_labels.txt**.
> Can you please help? @davide-coccomini @mesnico
> Please look into the **test.py of cross-efficient-vit** line **242-278**

This issue is being solved as the Original folder must contain the images cropped from original_sequence. Checking the empty tensor in line after 258 in test.py for batch size = 1 would fix the problem.
All issues are been solved!
Thanks a lot @davide-coccomini
