### ISSUE TITLE
Test set labels

### ISSUE THREAD

**Issue by hhle88** [davide-coccomini/Combining-EfficientNet-and-Vision-Transformers-for-Video-Deepfake-Detection#36]
Hello,
I just download DFDC test set from the link: https://www.kaggle.com/c/deepfake-detection-challenge/data. But the labels of them are not same as which shown in your file "dfdc_test_labels.csv"?
How should I do to get correct testing data set? 
Thank you very much!

**Comment by davide-coccomini** [comment]
Hello, you can find the correct official test set and labels on the website: https://dfdc.ai/login

You will need to download it using AWS.

**Comment by hhle88** [comment]
Many thanks.
It works well to me. Another good thing is that I now know how to use AWS CLI.
