### ISSUE TITLE
Convolutional Cross ViT architecture

### ISSUE THREAD

**Issue by thaondc** [davide-coccomini/Combining-EfficientNet-and-Vision-Transformers-for-Video-Deepfake-Detection#9]
Hi @davide-coccomini,

When I read your paper, I had a question about Cross ViT architecture. Can you help me to answer?
In your convolutional Cross ViT architecture, which used convolutional architecture by Wodajo and Atnafu, did you use pre-trained model, being from the author or train from scratch?

**Comment by davide-coccomini** [comment]
To carry out the tests with Convolutional ViT we used the pre-trained model of Wodajo. For our Cross Efficient ViT, we re-trained from 0.

**Comment by thaondc** [comment]
Thank you for your answer.
